inherit_from:
  - .rubocop_todo.yml

Layout/LineLength:
  Max: 300
  Exclude:
    - 'db/migrate/**/*'

Metrics/MethodLength:
  Max: 18
  Exclude:
    - 'db/migrate/**/*'

Metrics/BlockLength:
  Max: 90
  Exclude:
    - 'db/migrate/**/*'
  
Metrics/AbcSize:
  Max: 40   # 27 → 40 に上げる（もっと許容）

Style/Documentation:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
